In [1]:
import numpy as np
import random

In [2]:
a_1 = np.array([i for i in range(1, 11)], dtype=int)
print(a_1)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
a_2 = np.zeros((3, 3), dtype=int)
print(a_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
a_3 = np.random.randint(1, 11, (5, 5))
print(a_3)

[[ 1  8  8  3  9]
 [ 4  7  6  3  4]
 [ 4  2  3  9  3]
 [10  2  5  4 10]
 [ 1  3  6  1  6]]


In [5]:
a_4 = np.random.random((4, 4))
print(a_4)

[[0.40596095 0.46814453 0.58861579 0.29840596]
 [0.63973931 0.08616542 0.71672121 0.42703147]
 [0.2652617  0.44122431 0.8629037  0.15456288]
 [0.96094569 0.36091216 0.06003305 0.09120705]]


In [6]:
a_5_1 = np.random.randint(1, 11, (5,))
a_5_2 = np.random.randint(1, 11, (5,))
print(a_5_1, a_5_2)
a_5_add = a_5_1 + a_5_2
print(a_5_add)
a_5_sub = a_5_1 - a_5_2
print(a_5_sub)
a_5_mul = a_5_1 * a_5_2
print(a_5_mul)

[6 1 8 6 6] [1 2 1 3 6]
[ 7  3  9  9 12]
[ 5 -1  7  3  0]
[ 6  2  8 18 36]


In [7]:
a_6_1 = np.random.random((7,))
a_6_2 = np.random.random((7,))
print(a_6_1)
print(a_6_2)
a_6_dot = np.dot(a_6_1, a_6_2)
print(a_6_dot)

[0.02361272 0.91204261 0.2833188  0.4109309  0.97629624 0.89855082
 0.32225703]
[0.96925391 0.2527953  0.02135385 0.58156506 0.11845653 0.09903513
 0.48595961]
0.8597204715834785


In [8]:
a_7_1 = np.random.randint(1, 11, (2, 2))
a_7_2 = np.random.randint(1, 11, (2, 3))
print(a_7_1)
print(a_7_2)
a_7_dot = np.dot(a_7_1, a_7_2)
print(a_7_dot)

[[1 4]
 [9 1]]
[[8 7 4]
 [5 3 6]]
[[28 19 28]
 [77 66 42]]


In [11]:
a_8 = np.random.randint(1, 11, (3, 3))
print(a_8)
a_8_e = np.linalg.inv(a_8)
print(a_8_e)

[[1 3 6]
 [8 9 9]
 [5 8 4]]
[[-0.30769231  0.30769231 -0.23076923]
 [ 0.11111111 -0.22222222  0.33333333]
 [ 0.16239316  0.05982906 -0.12820513]]


In [12]:
a_9 = np.random.random((4, 4))
print(a_9)
a_9_t = a_9.T
print(a_9_t)

[[0.6931952  0.85527742 0.56593442 0.592249  ]
 [0.04157233 0.69889375 0.59479042 0.15065175]
 [0.87651362 0.46976934 0.96457126 0.83549194]
 [0.7022245  0.27200665 0.05537868 0.45295337]]
[[0.6931952  0.04157233 0.87651362 0.7022245 ]
 [0.85527742 0.69889375 0.46976934 0.27200665]
 [0.56593442 0.59479042 0.96457126 0.05537868]
 [0.592249   0.15065175 0.83549194 0.45295337]]


In [13]:
a_10_m = np.random.randint(1, 11, (3, 4))
print(a_10_m)
a_10_v = np.random.randint(1, 11, (4,))
print(a_10_v)
a_10_dot = np.dot(a_10_m, a_10_v)
print(a_10_dot)

[[ 7  5  1  9]
 [ 9 10  6  5]
 [ 4  5  1  5]]
[1 1 8 9]
[101 112  62]


In [14]:
a_11_m = np.random.random((2, 3))
print(a_11_m)
a_11_v = np.random.random((3,))
print(a_11_v)
a_11_dot = np.dot(a_11_m, a_11_v)
print(a_11_dot)

[[0.13993253 0.86187317 0.91351148]
 [0.66268058 0.87370785 0.76738397]]
[0.10048426 0.82730469 0.97160257]
[1.61466283 1.53500381]


In [15]:
a_12_1 = np.random.randint(1, 11, (2, 2))
print(a_12_1)
a_12_2 = np.random.randint(1, 11, (2, 2))
print(a_12_2)
a_12_mul = a_12_1 * a_12_2
print(a_12_mul)

[[5 8]
 [9 2]]
[[4 2]
 [9 8]]
[[20 16]
 [81 16]]


In [16]:
a_13_1 = np.random.randint(1, 11, (2, 2))
print(a_13_1)
a_13_2 = np.random.randint(1, 11, (2, 2))
print(a_13_2)
a_13_dot = np.dot(a_13_1, a_13_2)
print(a_13_dot)

[[3 9]
 [5 2]]
[[3 5]
 [1 1]]
[[18 24]
 [17 27]]


In [17]:
a_14 = np.random.randint(1, 101, (5, 5))
print(a_14)
a_14_sum = a_14.sum()
print(a_14_sum)

[[74 88 14 37 75]
 [20 59  7 68  9]
 [23 95  3 56 80]
 [27 50 96 61 88]
 [98  8 10  1 41]]
1188


In [18]:
a_15_1 = np.random.randint(1, 11, (4, 4))
print(a_15_1)
a_15_2 = np.random.randint(1, 11, (4, 4))
print(a_15_2)
a_15_sub = a_15_1 - a_15_2
print(a_15_sub)

[[ 1  5  1  4]
 [ 9  2  2 10]
 [ 5  5  2  6]
 [ 2  3  9  3]]
[[10  8  5  4]
 [ 1 10  9  6]
 [ 7  9  7  1]
 [ 7  8  5  9]]
[[-9 -3 -4  0]
 [ 8 -8 -7  4]
 [-2 -4 -5  5]
 [-5 -5  4 -6]]


In [20]:
a_16 = np.random.random((3, 3))
print(a_16)
vector = a_16.sum(axis=1)
print(vector)
vector = vector.reshape((3, 1))
print(vector)

[[0.73410075 0.42776762 0.08238212]
 [0.09482489 0.09586925 0.98907688]
 [0.85486656 0.26148651 0.57648063]]
[1.24425049 1.17977102 1.6928337 ]
[[1.24425049]
 [1.17977102]
 [1.6928337 ]]


In [21]:
a_17 = np.random.randint(1, 26, (3, 4))
print(a_17)
a_17_sq = a_17 ** 2
print(a_17_sq)

[[20 15 14  3]
 [22 20 20  3]
 [ 6  8 24 11]]
[[400 225 196   9]
 [484 400 400   9]
 [ 36  64 576 121]]


In [22]:
a_18 = np.random.randint(1, 51, (4,))
print(a_18)
a_18_rt = a_18 ** 0.5
print(a_18_rt)

[24 36  6  9]
[4.89897949 6.         2.44948974 3.        ]
